server:
  port: 8090

spring:
  application:
    name: pg-ms-auth
  datasource:
    url: jdbc:mysql://db-mysql:3310/auth_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: pulsegym
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        prefer-ip-address: false
        instance-id: ${spring.application.name}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
    protocol: smtp
    default-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: ${JWT_SECRET}
    token-expiration: 3600000
    reset-token-expiration-minutes: 10
    # frontend-url: http://localhost:3000
