server:
  port: 8090

spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:mysql://db-auth:3306/auth_db?allowPublicKeyRetrieval=true&useSSL=false
    username: pulsegym
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud: 
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        prefer-ip-address: false
        instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret: oMYOYPCjKGRjXEHQqcG0F/KwhgMZ7yej4cBdqeMVZsk=
    expiration: 3600000

