server:
  port: 8081

spring:
  application:
    name: ms-users

  datasource:
    url: jdbc:mysql://db-auth:3306/users_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: pulsegym
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        prefer-ip-address: false
        instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: oMYOYPCjKGRjXEHQqcG0F/KwhgMZ7yej4cBdqeMVZsk=
    token-expiration: 3600000
