server:
  port: 8082

spring:
  application:
    name: pg-ms-operation
    
  datasource:
    url: jdbc:mysql://db-mysql:3310/operations_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: pulsegym
    password: 123
  jpa: 
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        prefer-ip-address: false
        instance-id: ${spring.application.name}

microservicio:
  usuarios:
    url: http://pg-ms-users:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: ${JWT_SECRET}
    token-expiration: 3600000

logging:
  level:
    com.pulse_gym: DEBUG

biometric:
  jwt:
    secret-key: ${BIOMETRIC_JWT_SECRET:biometricSecretKeyForDemo}
    token-expiration: 300000   # 5 minutos en milisegundos